In [5]:
import pandas as pd

wine_reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

In [6]:
wine_reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [7]:
wine_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  str
 1   description            129971 non-null  str
 2   designation            92506 non-null   str
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  str
 6   region_1               108724 non-null  str
 7   region_2               50511 non-null   str
 8   taster_name            103727 non-null  str
 9   taster_twitter_handle  98758 non-null   str
 10  title                  129971 non-null  str
 11  variety                129970 non-null  str
 12  winery                 129971 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 12.9 MB

In [8]:
wine_reviews.describe()

              points          price
count  129971.000000  120975.000000
mean       88.447138      35.363389
std         3.039730      41.022218
min        80.000000       4.000000
25%        86.000000      17.000000
50%        88.000000      25.000000
75%        91.000000      42.000000
max       100.000000    3300.000000

In [9]:
wine_reviews.values

array([['Italy',
        "Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity.",
        'Vulkà Bianco', ..., 'Nicosia 2013 Vulkà Bianco  (Etna)',
        'White Blend', 'Nicosia'],
       ['Portugal',
        "This is ripe and fruity, a wine that is smooth while still structured. Firm tannins are filled out with juicy red berry fruits and freshened with acidity. It's  already drinkable, although it will certainly be better from 2016.",
        'Avidagos', ..., 'Quinta dos Avidagos 2011 Avidagos Red (Douro)',
        'Portuguese Red', 'Quinta dos Avidagos'],
       ['US',
        'Tart and snappy, the flavors of lime flesh and rind dominate. Some green pineapple pokes through, with crisp acidity underscoring the flavors. The wine was all stainless-steel fermented.',
        nan, ..., 'Rainstorm 2013 Pinot Gris (Willamette Valley)',
        'Pinot Gris', 'Rainstorm'],
       ...,
       ['France',
        'Well-drained gravel soil gives this wine its crisp and dry character. It is ripe and fruity, although the spice is subdued in favor of a more serious structure. This is a wine to age for a couple of years, so drink from 2017.',
        'Kritt', ...,
        'Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)',
        'Gewürztraminer', 'Domaine Gresser'],
       ['France',
        'A dry style of Pinot Gris, this is crisp with some acidity. It also has weight and a solid, powerful core of spice and baked apple flavors. With its structure still developing, the wine needs to age. Drink from 2015.',
        nan, ..., 'Domaine Marcel Deiss 2012 Pinot Gris (Alsace)',
        'Pinot Gris', 'Domaine Marcel Deiss'],
       ['France',
        'Big, rich and off-dry, this is powered by intense spiciness and rounded texture. Lychees dominate the fruit profile, giving an opulent feel to the aftertaste. Drink now.',
        'Lieu-dit Harth Cuvée Caroline', ...,
        'Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)',
        'Gewürztraminer', 'Domaine Schoffit']],
      shape=(129971, 13), dtype=object)

In [10]:
wine_reviews.loc[wine_reviews.country == "Italy", "points"]

0         87
6         87
13        87
22        87
24        87
          ..
129929    91
129943    90
129947    90
129961    90
129962    90
Name: points, Length: 19540, dtype: int64

In [11]:
wine_reviews.loc[wine_reviews.country.isin(["Italy", "France"]), ["points", "country", "description"]]

        points country                                        description
0           87   Italy  Aromas include tropical fruit, broom, brimston...
6           87   Italy  Here's a bright, informal red that opens with ...
7           87  France  This dry and restrained wine offers spice in p...
9           87  France  This has great depth of flavor with its fresh ...
11          87  France  This is a dry wine, very spicy, with a tight, ...
...        ...     ...                                                ...
129964      90  France  Initially quite muted, this wine slowly develo...
129965      90  France  While it's rich, this beautiful dry wine also ...
129968      90  France  Well-drained gravel soil gives this wine its c...
129969      90  France  A dry style of Pinot Gris, this is crisp with ...
129970      90  France  Big, rich and off-dry, this is powered by inte...

[41633 rows x 3 columns]

In [12]:
wine_reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='str')

In [13]:
wine_reviews.index

RangeIndex(start=0, stop=129971, step=1)

In [14]:
wine_reviews.size

1689623

In [15]:
wine_reviews.shape

(129971, 13)

In [16]:
wine_reviews.dtypes

country                      str
description                  str
designation                  str
points                     int64
price                    float64
province                     str
region_1                     str
region_2                     str
taster_name                  str
taster_twitter_handle        str
title                        str
variety                      str
winery                       str
dtype: object