In [2]:
import pandas as pd

reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

In [4]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
#Pandas provides many simple "summary functions" (not an official name) which restructure the data in some useful way.
# For example, consider the describe() method:
#This method generates a high-level summary of the attributes of the given column.
# It is type-aware, meaning that its output changes based on the data type of the input.


reviews.points.describe()

count    129971.000000
mean         88.447138
std           3.039730
min          80.000000
25%          86.000000
50%          88.000000
75%          91.000000
max         100.000000
Name: points, dtype: float64

In [6]:
# The output above only makes sense for numerical data; for string data here's what we get
reviews.taster_name.describe()

count         103727
unique            19
top       Roger Voss
freq           25514
Name: taster_name, dtype: object

In [7]:
#to see the mean of the points allotted (e.g. how well an averagely rated wine does), we can use the mean() function:
reviews.points.mean()

np.float64(88.44713820775404)

In [8]:
#To see a list of unique values we can use the unique() function:
reviews.taster_name.unique()

<StringArray>
[     'Kerin O’Keefe',         'Roger Voss',       'Paul Gregutt',
 'Alexander Peartree',  'Michael Schachner', 'Anna Lee C. Iijima',
     'Virginie Boone',      'Matt Kettmann',                  nan,
   'Sean P. Sullivan',         'Jim Gordon',     'Joe Czerwinski',
   'Anne Krebiehl MW',      'Lauren Buzzeo',      'Mike DeSimone',
       'Jeff Jenssen',    'Susan Kostrzewa',       'Carrie Dykes',
        'Fiona Adams',  'Christina Pickard']
Length: 20, dtype: str

In [9]:
#To see a list of unique values and how often they occur in the dataset, we can use the value_counts() method:
reviews.taster_name.value_counts()

taster_name
Roger Voss            25514
Michael Schachner     15134
Kerin O’Keefe         10776
Virginie Boone         9537
Paul Gregutt           9532
Matt Kettmann          6332
Joe Czerwinski         5147
Sean P. Sullivan       4966
Anna Lee C. Iijima     4415
Jim Gordon             4177
Anne Krebiehl MW       3685
Lauren Buzzeo          1835
Susan Kostrzewa        1085
Mike DeSimone           514
Jeff Jenssen            491
Alexander Peartree      415
Carrie Dykes            139
Fiona Adams              27
Christina Pickard         6
Name: count, dtype: int64

In [ ]:
#Maps
#A map is a term, borrowed from mathematics,
# for a function that takes one set of values and "maps" them to another set of values
#In data science we often have a need for creating new representations from existing data,
# or for transforming data from the format it is in now to the format that we want it to be in later.
# Maps are what handle this work, making them extremely important for getting your work done!

#There are two mapping methods that you will use often.
map() #is the first, and slightly simpler one. For example, suppose that we wanted to remean the scores
#the wines received to 0. We can do this as follows:

In [10]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p : p - review_points_mean)

0        -1.447138
1        -1.447138
2        -1.447138
3        -1.447138
4        -1.447138
            ...
129966    1.552862
129967    1.552862
129968    1.552862
129969    1.552862
129970    1.552862
Name: points, Length: 129971, dtype: float64

In [ ]:
"""The code snippet calculates the average of the
points column in a pandas DataFrame called reviews, and then creates a new Series where each original data point is replaced by its
difference from that average. 
Here is a breakdown of the two parts:

    review_points_mean = reviews.points.mean()
        This line calculates the mean (average) of all values in the points column of the reviews DataFrame. The result, which is a
        single scalar number, is stored in the variable review_points_mean.
    reviews.points.map(lambda p : p - review_points_mean)
        This line uses the pandas .map() function to apply an operation to every single element in the points column.
        lambda p : p - review_points_mean is a small, anonymous function (a lambda function) that takes one argument,
        p (representing an individual point value from the series), and returns that value minus the pre-calculated review_points_mean.
        The .map() method iterates through the entire reviews.points Series, passes each element to the lambda function, and collects
        the results into a new pandas Series, effectively normalizing the data around the mean by showing how far each point is above
        or below the average
This technique is often used in data preprocessing to center the data around zero, which can be helpful for various machine learning
algorithms and statistical analyses."""

In [11]:
#apply() is the equivalent method if we want to transform a whole DataFrame by calling a custom method on each row or column.
# For example, if we wanted to create a new column called critic_level which categorizes the critic as "high" if they have given
# more than 100 reviews and "low" otherwise, we could do this:

def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis="columns")

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.447138,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.447138,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.447138,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.447138,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.447138,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Notes of honeysuckle and cantaloupe sweeten th...,Brauneberger Juffer-Sonnenuhr Spätlese,1.552862,28.0,Mosel,NaN,NaN,Anna Lee C. Iijima,NaN,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef)
129967,US,Citation is given as much as a decade of bottl...,NaN,1.552862,75.0,Oregon,Oregon,Oregon Other,Paul Gregutt,@paulgwine,Citation 2004 Pinot Noir (Oregon),Pinot Noir,Citation
129968,France,Well-drained gravel soil gives this wine its c...,Kritt,1.552862,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,Gewürztraminer,Domaine Gresser
129969,France,"A dry style of Pinot Gris, this is crisp with ...",NaN,1.552862,32.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),Pinot Gris,Domaine Marcel Deiss
129970,France,"Big, rich and off-dry, this is powered by inte...",Lieu-dit Harth Cuvée Caroline,1.552862,21.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,Gewürztraminer,Domaine Schoffit

In [ ]:
#question 1
#I'm an economical wine buyer. Which wine is the "best bargain"? 
# Create a variable bargain_wine with the title of the wine with the highest points-to-price ratio in the dataset
#The pandas.idxmax() function returns the index label of the first occurrence of the maximum value over the requested axis.

bargain_idx = (reviews.points / reviews.price).idxmax()
bargain_wine = reviews.loc[bargain_idx, "title"]

bargain_wine

'Bandit NV Merlot (California)'

In [7]:
#question 2
#There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"?
# Create a Series descriptor_counts counting how many times each of these two words appears in the description column in the dataset.
# (For simplicity, let's ignore the capitalized versions of these words.)

n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])

descriptor_counts

tropical    3607
fruity      9090
dtype: int64

In [9]:
"""We'd like to host these wine reviews on our website, but a rating system ranging from 80 to 100 points is too hard to understand 
- we'd like to translate them into simple star ratings. A score of 95 or higher counts as 3 stars, a score of at least 85 but less
than 95 is 2 stars. Any other score is 1 star.

Also, the Canadian Vintners Association bought a lot of ads on the site, so any wines from Canada should automatically get 3 stars,
regardless of points.

Create a series star_ratings with the number of stars corresponding to each review in the dataset."""

def stars(row):
    if row.country == 'Canada':
        return 3
    elif row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1
    
star_ratings = reviews.apply(stars, axis='columns')
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

In [2]:
#Test questions 
import pandas as pd

reviews = pd.read_csv("winemag-data-130k-v2.csv", index_col=0)

In [3]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks